name: BedWars2023-Manager
version: '${project.version}'
main: me.agentkiiya.bwmanager.Manager
softdepend: [ BedWars2023, BWProxy2023 ]
authors: [ Agent, Kiiya ]
description: An addon for the BedWars2023 plugin that implements functionalities like Addon Manager, Arena Manager, Stats Manager, etc.
commands:
  bwm:
    aliases: bwmanager
    description: Main command for BedWars2023-Manager
